/* Dump the open file's token catalog as JavaScript, so scripts can refer to the
   user's own design system by name instead of typing hex.

     peirce-run tokens-pull | sed 's/^\[LOG\] //' > <kit>/skills/penpot-mcp/lib/tokens.js

   Everything on TokenCatalog is a getter, so it serialises as {} and has to be
   walked by documented member rather than by Object.keys. */
var CAT = penpot.library.local.tokens, sets = CAT.sets || [], rows = [], names = {};
for (var i = 0; i < sets.length; i++) {
  var set = sets[i], toks = set.tokens || [];
  for (var j = 0; j < toks.length; j++) {
    var t = toks[j];
    rows.push([set.name, t.type, t.name, t.value]);
    names[t.name] = t.value;
  }
}
console.log('/* GENERATED by tokens-pull from ' + penpot.currentFile.name +
            ' — ' + rows.length + ' tokens across ' + sets.length + ' sets */\n' +
            'var TOKS = ' + JSON.stringify(rows) + ';\n' +
            'var TOK = ' + JSON.stringify(names) + ';\n');
